// Location of the storage state generated by tests/auth.setup.ts.
// Single source of truth: playwright.config.ts (which projects load it from)
// and auth.setup.ts (which writes it) both import this path.
export const authFile = 'playwright/.auth/standard-user.json';
